const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.Fade,
		C3.Behaviors.MoveTo,
		C3.Behaviors.LOS,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Behaviors.solid,
		C3.Plugins.Mouse,
		C3.Plugins.TiledBg,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SetVectorX,
		C3.Behaviors.EightDir.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.EightDir.Acts.SetVectorY,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Text.Acts.SetX,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.MoveTo.Cnds.IsEnabled,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Behaviors.LOS.Cnds.RayIntersected,
		C3.Behaviors.LOS.Acts.SetRange,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.MoveTo.Cnds.CompareSpeed,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.AddChild
	];
};
self.C3_JsPropNameTable = [
	{"8Direction": 0},
	{ScrollTo: 0},
	{cybergirl: 0},
	{Fade: 0},
	{Nana: 0},
	{stoptime: 0},
	{Action: 0},
	{prevAction: 0},
	{MoveTo: 0},
	{LineOfSight: 0},
	{Bug: 0},
	{Keyboard: 0},
	{HP: 0},
	{Solid: 0},
	{Blacker: 0},
	{testBox: 0},
	{testBOX_2: 0},
	{classroom: 0},
	{tree: 0},
	{attack_1: 0},
	{attack_2: 0},
	{ULT: 0},
	{sawp: 0},
	{Mouse: 0},
	{BG: 0},
	{bugHp: 0},
	{battle_cybergirl: 0},
	{battle_bug: 0},
	{sawp_B: 0},
	{ULT_text: 0},
	{test_text: 0},
	{win: 0},
	{win_BG: 0},
	{lost: 0},
	{TiledBackground: 0},
	{Bug_Boss: 0},
	{chiger: 0},
	{aa: 0},
	{end: 0},
	{next: 0},
	{LV1BG: 0},
	{TiledBackground2: 0},
	{hallwayBG: 0},
	{Sprite: 0},
	{hallway: 0},
	{IDK: 0},
	{Tdesk: 0},
	{Tchair: 0},
	{Battle_bugboss: 0},
	{playButtin: 0},
	{TitleBG: 0},
	{restart: 0},
	{Text: 0},
	{code: 0},
	{stares: 0},
	{textbox_BG: 0},
	{textbox: 0},
	{BACKbattle1: 0},
	{NanaHP: 0},
	{nanabox: 0},
	{notFinished: 0},
	{cyberboy07: 0},
	{bug_flying: 0},
	{lowersubwaylo: 0},
	{wakeway: 0},
	{homedoor: 0},
	{tockbox: 0},
	{waterpond: 0},
	{subwaylayout: 0},
	{homelayout2: 0},
	{CH: 0},
	{TH: 0},
	{TVH: 0},
	{SS: 0},
	{sa: 0},
	{walkwayBG: 0},
	{hallwayB: 0},
	{hallway2: 0},
	{hallwayA: 0},
	{bathroomBG: 0},
	{back: 0},
	{gotolv1: 0},
	{gotoBR: 0},
	{gotogen: 0},
	{genroomBG: 0},
	{gotoclass: 0},
	{gotohallway: 0},
	{gotohallway2: 0},
	{rellway: 0},
	{rellway2: 0},
	{lond: 0},
	{StartFand: 0},
	{cMrmr: 0},
	{DamageSlash: 0},
	{TEST_battle: 0},
	{Rooftop2: 0},
	{Rooftop: 0},
	{OlivePenguin144: 0},
	{Audio: 0},
	{Sprite2: 0},
	{Hp: 0},
	{enemiesHP: 0},
	{attack: 0},
	{bug_kill: 0},
	{AttackDelay: 0},
	{BossKilled: 0},
	{OlivePenguin144Killed: 0},
	{Music: 0},
	{fiying: 0}
];

self.InstanceType = {
	cybergirl: class extends self.ISpriteInstance {},
	Nana: class extends self.ISpriteInstance {},
	Bug: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	HP: class extends self.ITextInstance {},
	Blacker: class extends self.ISpriteInstance {},
	testBox: class extends self.ISpriteInstance {},
	testBOX_2: class extends self.ISpriteInstance {},
	classroom: class extends self.ISpriteInstance {},
	tree: class extends self.ISpriteInstance {},
	attack_1: class extends self.ISpriteInstance {},
	attack_2: class extends self.ISpriteInstance {},
	ULT: class extends self.ISpriteInstance {},
	sawp: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	BG: class extends self.ITiledBackgroundInstance {},
	bugHp: class extends self.ITextInstance {},
	battle_cybergirl: class extends self.ISpriteInstance {},
	battle_bug: class extends self.ISpriteInstance {},
	sawp_B: class extends self.ISpriteInstance {},
	ULT_text: class extends self.ITextInstance {},
	test_text: class extends self.ITextInstance {},
	win: class extends self.ITextInstance {},
	win_BG: class extends self.ITiledBackgroundInstance {},
	lost: class extends self.ITextInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Bug_Boss: class extends self.ISpriteInstance {},
	chiger: class extends self.ISpriteInstance {},
	aa: class extends self.ISpriteInstance {},
	end: class extends self.ISpriteInstance {},
	next: class extends self.ISpriteInstance {},
	LV1BG: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	hallwayBG: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	hallway: class extends self.ITiledBackgroundInstance {},
	IDK: class extends self.ITiledBackgroundInstance {},
	Tdesk: class extends self.ISpriteInstance {},
	Tchair: class extends self.ISpriteInstance {},
	Battle_bugboss: class extends self.ISpriteInstance {},
	playButtin: class extends self.ISpriteInstance {},
	TitleBG: class extends self.ISpriteInstance {},
	restart: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	code: class extends self.ISpriteInstance {},
	stares: class extends self.ISpriteInstance {},
	textbox_BG: class extends self.ISpriteInstance {},
	textbox: class extends self.ITextInstance {},
	BACKbattle1: class extends self.ISpriteInstance {},
	NanaHP: class extends self.ITextInstance {},
	nanabox: class extends self.ISpriteInstance {},
	notFinished: class extends self.ITextInstance {},
	cyberboy07: class extends self.ISpriteInstance {},
	bug_flying: class extends self.ISpriteInstance {},
	lowersubwaylo: class extends self.ISpriteInstance {},
	wakeway: class extends self.ISpriteInstance {},
	homedoor: class extends self.ISpriteInstance {},
	tockbox: class extends self.ISpriteInstance {},
	waterpond: class extends self.ISpriteInstance {},
	subwaylayout: class extends self.ISpriteInstance {},
	homelayout2: class extends self.ISpriteInstance {},
	CH: class extends self.ISpriteInstance {},
	TH: class extends self.ISpriteInstance {},
	TVH: class extends self.ISpriteInstance {},
	SS: class extends self.ISpriteInstance {},
	sa: class extends self.ISpriteInstance {},
	walkwayBG: class extends self.ISpriteInstance {},
	hallwayB: class extends self.ISpriteInstance {},
	hallway2: class extends self.ISpriteInstance {},
	hallwayA: class extends self.ISpriteInstance {},
	bathroomBG: class extends self.ISpriteInstance {},
	back: class extends self.ISpriteInstance {},
	gotolv1: class extends self.ISpriteInstance {},
	gotoBR: class extends self.ISpriteInstance {},
	gotogen: class extends self.ISpriteInstance {},
	genroomBG: class extends self.ISpriteInstance {},
	gotoclass: class extends self.ISpriteInstance {},
	gotohallway: class extends self.ISpriteInstance {},
	gotohallway2: class extends self.ISpriteInstance {},
	rellway: class extends self.ISpriteInstance {},
	rellway2: class extends self.ISpriteInstance {},
	lond: class extends self.ISpriteInstance {},
	StartFand: class extends self.ISpriteInstance {},
	cMrmr: class extends self.ISpriteInstance {},
	DamageSlash: class extends self.ISpriteInstance {},
	TEST_battle: class extends self.ISpriteInstance {},
	Rooftop2: class extends self.ISpriteInstance {},
	Rooftop: class extends self.ISpriteInstance {},
	OlivePenguin144: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {}
}